"""Playbook: detect → prescribe → **install the fix**.

Every other tool in this space stops at the second arrow. AgentLens generates a
ranked, ready-to-paste rules file from the user's own findings — the thing they
actually add to ``CLAUDE.md`` / ``AGENTS.md`` / ``.junie/guidelines.md`` so the
habit stops recurring, rather than a report they read once and forget.

Two sections, deliberately kept separate — in the CLI, in the dashboard, and in
every rendered file:

1. **Personalised rules** (this module's reason to exist): generated from the
   user's own `Finding`s, ranked by dollar evidence, capped at `DEFAULT_LIMIT`.
   Nobody else can produce this section — it requires the user's own data.
2. **Curated reference** (`CURATED_REFERENCE` below): general agent-cost
   hygiene, static and hand-written. Genuinely useful, but anyone could write
   it — no data moat — so it renders visually secondary everywhere.
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Any

from .detectors.base import Finding

#: A 30-rule guidelines file is itself context bloat — the exact failure mode
#: this tool exists to catch. Capping keeps the output something a model will
#: actually read and follow rather than skim.
DEFAULT_LIMIT = 8


@dataclass(slots=True)
class Rule:
    text: str          # the rule, imperative, ready to paste as-is
    source: str         # detector name that produced it
    evidence_usd: float
    occurrences: int
    rationale: str      # one line: why, grounded in the user's own data

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def build_playbook(findings: list[Finding], limit: int = DEFAULT_LIMIT) -> list[Rule]:
    """One rule per finding, already ranked by `run_all` (dollar-descending).

    `Finding.prescription` already satisfies the three-part contract every
    detector obeys (own words behind it via evidence, a dollar figure, one
    concrete rewrite) — the playbook doesn't re-derive advice, it packages the
    existing prescriptions as an installable file.
    """
    rules = [
        Rule(
            text=f.prescription,
            source=f.detector,
            evidence_usd=round(f.wasted_usd, 4),
            occurrences=f.occurrences,
            rationale=(
                f"Found {f.occurrences}× in your history, "
                f"${f.wasted_usd:.2f} traced to it. {f.mechanism}"
            ),
        )
        for f in findings
        if f.prescription
    ]
    rules.sort(key=lambda r: (-r.evidence_usd, -r.occurrences))
    return rules[:limit]


# --- rendering --------------------------------------------------------------

_HEADERS = {
    "claude": "# Guidelines (generated by AgentLens)\n\n"
              "Rules below are ranked by what they've actually cost this project's "
              "sessions — not generic advice.\n",
    "agents": "# AGENTS.md — cost & workflow guidelines (generated by AgentLens)\n\n"
              "Follow these when working in this repo; each is backed by measured cost, "
              "not opinion.\n",
    "junie": "# Junie guidelines (generated by AgentLens)\n\n"
             "Ranked by measured cost impact in this project's session history.\n",
    "markdown": "# AgentLens Playbook\n",
}


def render(rules: list[Rule], fmt: str = "markdown", include_reference: bool = True) -> str:
    """Render the personalised section, then (if requested) the curated
    reference below it, clearly separated — never interleaved, so a reader can
    tell at a glance which lines are backed by their own data and which are
    general advice."""
    if fmt not in _HEADERS:
        raise ValueError(f"unknown playbook format: {fmt!r} (choose from {sorted(_HEADERS)})")

    lines = [_HEADERS[fmt]]

    if not rules:
        lines.append(
            "\nNo recurring waste patterns found yet. Run `agentlens ingest` after a few "
            "more sessions and regenerate.\n"
        )
    else:
        lines.append("\n## Rules from your own history\n")
        for r in rules:
            evidence_comment = f"<!-- ${r.evidence_usd:.2f} across {r.occurrences} call(s) -->"
            lines.append(f"\n- {r.text}\n  {evidence_comment}")
        lines.append("\n")

    if include_reference:
        lines.append("\n---\n")
        lines.append(CURATED_REFERENCE)

    return "".join(lines) + "\n"


# --- curated reference (static, no data moat — kept short on purpose) -------

CURATED_REFERENCE = """\
## General reference (not derived from your data)

Baseline habits worth keeping regardless of what the detectors above find:

- Start a fresh session per topic; don't let one session drift across
  unrelated tasks. Compaction is a safety net, not a workflow.
- Name the file and the acceptance check in the first prompt of a task, not
  after the agent guesses wrong once.
- Prefer diffs over whole-file pastes when giving the agent context on a
  change someone else made.
- Route mechanical, single-file, clearly-specified edits to a cheaper model;
  reserve the frontier model for design and debugging.
- Re-run `agentlens waste` periodically — habits drift, and what was fine
  last month may not be this month.
"""
